export const POPULAR_COURSES = [
  "TIET — Undergraduate Programs",
  "B.E. Computer Engineering",
  "B.E. Computer Science & Engineering",
  "B.E. Computer Science & Business Systems",
  "B.E. Chemical Engineering",
  "B.E. Civil Engineering",
  "B.E. Electrical Engineering",
  "B.E. Electronics & Communication Engineering",
  "B.E. Electronics & Computer Engineering",
  "B.E. Electronics (Instrumentation & Control) Engineering",
  "B.E. Mechanical Engineering",
  "B.E. Mechatronics",
  "B.E. Robotics & Artificial Intelligence",
  "B.E. Electrical & Computer Engineering",
  "B.Tech. Biotechnology",
  "B.Tech. Biomedical Engineering",
  "B.E. / B.Tech. Lateral Entry",
  "TIET — Postgraduate Programs",
  "M.E. / M.Tech.",
  "M.Sc.",
  "M.A.",
  "MBA",
  "MCA",
  "TIET — Doctoral Programs",
  "Ph.D.",
  "D.Sc.",
  "TIET — Dual Degree",
  "B.E. – MBA",
  "TSLAS — Undergraduate Programs",
  "Bachelor of Arts (B.A.)",
  "Bachelor of Science (B.Sc.)",
  "Bachelor of Business Administration (BBA)",
  "Bachelor of Commerce (B.Com)",
  "TSLAS — Majors",
  "BBA",
  "B.Com",
  "Biotechnology",
  "Chemistry",
  "Cognitive Science",
  "Computer Sciences",
  "Data Science & AI",
  "Economics",
  "Environment & Sustainability",
  "History",
  "Literary & Cultural Studies",
  "Mathematics",
  "Mathematics & Computing",
  "Philosophy",
  "Physics",
  "Political Science",
  "Psychology",
  "Sociology",
  "Geography & Resource Management",
  "Astrophysics & Space Science",
  "TSLAS — Postgraduate Program",
  "M.A. Psychology",
  "Clinical Psychology",
  "Counseling Psychology",
  "Industrial & Organizational Psychology",
  "TSLAS — Doctoral Program",
  "Ph.D. (TSLAS)",
  "TPC — Diploma Programs",
  "Diploma in Computer Science & Engineering",
  "Diploma in Mechanical Engineering",
  "Diploma in Electrical Engineering",
  "Diploma in Civil Engineering",
  "Diploma in Architectural Assistantship",
  "3-Year Diploma Programs"
];

